// Static data for Fire TV app

export const clubs = [
  {
    id: '1',
    name: 'Movie Nights',
    image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
    members: 1427,
    isLive: true,
    movies: ['1', 'tc-1', '3'],
  },
  {
    id: '2',
    name: 'Sports Club',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
    members: 684,
    isLive: false,
    movies: ['2', 'tc-2'],
  },
  {
    id: '3',
    name: 'Comedy Central',
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
    members: 634,
    isLive: true,
    movies: ['3'],
  },
  {
    id: '4',
    name: 'Documentaries',
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
    members: 421,
    isLive: false,
    movies: ['1', '2'],
  },
];

export const trendingVideos = [
  {
    id: '1',
    title: 'The Latest Blockbuster Review',
    channel: 'SuperCinema',
    thumbnail: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80',
    views: '24k',
    time: '4h ago',
    isLive: false,
    description: 'A deep dive into the latest blockbuster movie, exploring its themes, characters, and impact on the film industry.',
    rating: 4.5,
    reviews: [
      { id: 'rev1', user: 'CinemaFan', comment: 'Absolutely amazing! A must-watch for everyone.' },
      { id: 'rev2', user: 'MovieCritic', comment: 'A bit overhyped, but still a solid film.' },
    ],
    plot: 'In a world where movies are reviewed, one reviewer goes on a meta-journey to review the concept of reviewing itself, questioning the very fabric of cinematic critique.',
    actors: ['Reviewer Rick', 'Cinephile Cindy', 'Director Dave'],
    genre: 'Meta-Comedy',
    director: 'Frank Filmman',
  },
  {
    id: '2',
    title: 'Championship Game Highlights',
    channel: 'champion game',
    thumbnail: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
    views: '18k',
    time: '2h ago',
    isLive: false,
    description: 'Relive the most exciting moments from the championship game, with expert commentary and analysis.',
    rating: 4.8,
    reviews: [
      { id: 'rev3', user: 'SportsNut', comment: 'Incredible game! I was on the edge of my seat the whole time.' },
    ],
    plot: 'Two teams clash in an epic battle for the championship title. With everything on the line, heroes will rise and legends will be born in this unforgettable contest.',
    actors: ['Quarterback Mike', 'Kicker Jenny', 'Coach Steve'],
    genre: 'Sports',
    director: 'Vince Gridiron',
  },
  {
    id: '3',
    title: 'Stand-Up Comedy Special',
    channel: 'comedy corner',
    thumbnail: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b41?auto=format&fit=crop&w=400&q=80',
    views: '40k',
    time: 'LIVE',
    isLive: true,
    description: 'A hilarious stand-up special from one of the world\'s most popular comedians. Get ready to laugh!',
    rating: 4.2,
    reviews: [
      { id: 'rev4', user: 'FunnyGal', comment: 'Laughed so hard I cried! A comic genius.' },
      { id: 'rev5', user: 'SeriousSimon', comment: 'Not my cup of tea, but I can see why people like it.' },
    ],
    plot: 'A comedian takes the stage to deliver a side-splitting performance, tackling everything from everyday life to the absurdities of the modern world. No topic is off-limits.',
    actors: ['Comedian Chris'],
    genre: 'Comedy',
    director: 'Lisa Laughs',
  },
  {
    id: '4',
    title: 'Galactic Odyssey',
    channel: 'SpaceVision',
    thumbnail: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=400&q=80',
    views: '12k',
    time: '1d ago',
    isLive: false,
    description: 'A journey through the stars with a crew of misfits.',
    rating: 4.7,
    reviews: [],
    plot: 'A ragtag crew explores the galaxy, facing cosmic threats and forging unlikely friendships.',
    actors: ['Star Captain', 'Alien Ally'],
    genre: 'Sci-Fi',
    director: 'Nova Star',
  },
  {
    id: '5',
    title: 'Haunted Manor',
    channel: 'SpookTV',
    thumbnail: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=400&q=80',
    views: '9k',
    time: '3d ago',
    isLive: false,
    description: 'A chilling tale of a haunted house.',
    rating: 4.1,
    reviews: [],
    plot: 'A family moves into a manor with a dark past. Ghostly secrets unravel.',
    actors: ['Ghost Hunter', 'Scared Mom'],
    genre: 'Horror',
    director: 'Chill McScary',
  },
  {
    id: '6',
    title: 'The Chef Showdown',
    channel: 'Foodies',
    thumbnail: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    views: '15k',
    time: '5h ago',
    isLive: false,
    description: 'Top chefs compete for culinary glory.',
    rating: 4.6,
    reviews: [],
    plot: 'Chefs from around the world face off in a high-stakes kitchen battle.',
    actors: ['Chef Pierre', 'Chef Maria'],
    genre: 'Reality',
    director: 'Gordon Flambé',
  },
  {
    id: '7',
    title: 'Lost in the Jungle',
    channel: 'AdventureX',
    thumbnail: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
    views: '7k',
    time: '2d ago',
    isLive: false,
    description: 'Survivors must find their way out of a mysterious jungle.',
    rating: 4.3,
    reviews: [],
    plot: 'A plane crash leaves strangers stranded in a jungle full of secrets.',
    actors: ['Explorer Joe', 'Guide Ana'],
    genre: 'Adventure',
    director: 'Jungle Jim',
  },
  {
    id: '8',
    title: 'City Lights',
    channel: 'UrbanTV',
    thumbnail: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
    views: '22k',
    time: '6h ago',
    isLive: false,
    description: 'A drama about life in the big city.',
    rating: 4.0,
    reviews: [],
    plot: 'Intertwined stories of city dwellers chasing their dreams.',
    actors: ['City Girl', 'Taxi Driver'],
    genre: 'Drama',
    director: 'Urban Smith',
  },
  {
    id: '9',
    title: 'The Great Heist',
    channel: 'CrimeTime',
    thumbnail: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
    views: '30k',
    time: '8h ago',
    isLive: false,
    description: 'A team plans the ultimate bank robbery.',
    rating: 4.8,
    reviews: [],
    plot: 'Masterminds and misfits team up for a high-stakes heist.',
    actors: ['The Mastermind', 'The Hacker'],
    genre: 'Crime',
    director: 'Heist King',
  },
  {
    id: '10',
    title: 'Wildlife Wonders',
    channel: 'NatureDoc',
    thumbnail: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b41?auto=format&fit=crop&w=400&q=80',
    views: '11k',
    time: '1w ago',
    isLive: false,
    description: 'A documentary about the wonders of wildlife.',
    rating: 4.9,
    reviews: [],
    plot: 'Explore the most amazing animals and their habitats.',
    actors: ['Narrator'],
    genre: 'Documentary',
    director: 'Doc Wild',
  },
  {
    id: '11',
    title: 'Retro Rewind',
    channel: 'ClassicTV',
    thumbnail: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
    views: '5k',
    time: '3d ago',
    isLive: false,
    description: 'A look back at classic TV shows.',
    rating: 4.2,
    reviews: [],
    plot: 'Relive the golden age of television with this nostalgic series.',
    actors: ['Host Bob'],
    genre: 'History',
    director: 'Retro Ray',
  },
  {
    id: '12',
    title: 'Future Tech',
    channel: 'TechNow',
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
    views: '19k',
    time: '12h ago',
    isLive: false,
    description: 'Exploring the technology of tomorrow.',
    rating: 4.4,
    reviews: [],
    plot: 'A deep dive into innovations shaping our future.',
    actors: ['Tech Guru'],
    genre: 'Science',
    director: 'Futurist Fran',
  },
  {
    id: '13',
    title: 'Dance Fever',
    channel: 'MoveIt',
    thumbnail: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
    views: '13k',
    time: '2d ago',
    isLive: false,
    description: 'A dance competition with the best crews.',
    rating: 4.5,
    reviews: [],
    plot: 'Dance crews battle for the top spot in this high-energy show.',
    actors: ['Judge Lisa', 'Dancer Mike'],
    genre: 'Reality',
    director: 'Groove Master',
  },
  {
    id: '14',
    title: 'Undercover Agent',
    channel: 'SpyTV',
    thumbnail: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=400&q=80',
    views: '17k',
    time: '4d ago',
    isLive: false,
    description: 'A spy goes deep undercover to stop a global threat.',
    rating: 4.6,
    reviews: [],
    plot: 'Espionage, danger, and double-crosses in this thrilling series.',
    actors: ['Agent X', 'Villain V'],
    genre: 'Thriller',
    director: 'Spy Master',
  },
  {
    id: '15',
    title: 'Family Ties',
    channel: 'DramaHouse',
    thumbnail: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
    views: '8k',
    time: '5d ago',
    isLive: false,
    description: 'A heartfelt drama about family bonds.',
    rating: 4.3,
    reviews: [],
    plot: 'Generations clash and connect in this emotional family saga.',
    actors: ['Grandma Rose', 'Young Tim'],
    genre: 'Drama',
    director: 'Heart String',
  },
];

export const users = [
  {
    id: '1',
    name: 'Malti',
    username: 'emma.artist',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    meta: 'Art | 5 mutual friends',
  },
  {
    id: '2',
    name: 'Mike Thompson',
    username: 'tech_mike',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    meta: 'Technology | 4 mutual friends',
  },
  {
    id: '3',
    name: 'Jordan Lee',
    username: 'music_lover',
    avatar: 'https://randomuser.me/api/portraits/men/41.jpg',
    meta: 'Music | 2 mutual friends',
  },
  {
    id: '4',
    name: 'Alice Johnson',
    username: 'alice.j',
    avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
    meta: '12 mutual friends',
  },
  {
    id: '5',
    name: 'Bob Smith',
    username: 'bob.smith',
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    meta: '8 mutual friends',
  },
  {
    id: '6',
    name: 'Carol Martinez',
    username: 'carol_m',
    avatar: 'https://randomuser.me/api/portraits/women/33.jpg',
    meta: '6 mutual friends',
  },
  {
    id: '7',
    name: 'David Kim',
    username: 'david.k',
    avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    meta: '2 mutual friends',
  },
];

export const stories = [
  {
    id: '1',
    username: 'Your Story',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    video: 'https://assets.mixkit.co/videos/preview/mixkit-mysterious-pale-looking-fashion-woman-at-winter-44321-large.mp4',
    movieTitle: 'Winter Tale',
    caption: 'Feeling the winter vibes! ❄️',
    isCurrentUser: true,
  },
  ...users.slice(0, 5).map((user, index) => ({
    id: (index + 2).toString(),
    username: user.name.split(' ')[0],
    avatar: user.avatar,
    video: 'https://assets.mixkit.co/videos/preview/mixkit-waves-in-the-water-1164-large.mp4',
    movieTitle: 'Ocean Waves',
    caption: 'Loved it!!',
    isCurrentUser: false,
  })),
];

export const recommendedForYou = trendingVideos.map(video => ({
  ...video,
  id: `rec-${video.id}`,
})).reverse();

export const hotHits = [...trendingVideos].sort((a, b) => {
  const viewsA = parseInt(a.views.replace('k', '000'));
  const viewsB = parseInt(b.views.replace('k', '000'));
  return viewsB - viewsA;
}).map(video => ({ ...video, id: `hot-${video.id}` }));

export const moreOfWhatYouLike = clubs.map(club => ({
  ...club,
  id: `more-${club.id}`,
}));

export const popularTomCruise = [
  {
    id: 'tc-1',
    title: 'Mission Impossible: Fallout',
    channel: 'Paramount Pictures',
    thumbnail: 'https://images.unsplash.com/photo-1578949232808-3162a046c4f7?auto=format&fit=crop&w=400&q=80',
    views: '1.2M',
    time: '2 years ago',
    isLive: false,
    description: 'Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.',
    rating: 4.9,
    reviews: [
      { id: 'rev6', user: 'ActionFan', comment: 'One of the best action movies ever made!' },
      { id: 'rev7', user: 'TomCruiseFan', comment: 'Tom Cruise is a legend!' },
    ],
    plot: 'When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfill his original briefing, the CIA begins to question his loyalty and his motives. The IMF team must race against time, hunted by assassins and former allies while trying to prevent a global catastrophe.',
    actors: ['Tom Cruise', 'Henry Cavill', 'Ving Rhames', 'Simon Pegg'],
    genre: 'Action, Thriller',
    director: 'Christopher McQuarrie',
  },
  {
    id: 'tc-2',
    title: 'Top Gun: Maverick',
    channel: 'Skydance Media',
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-9596468b635f?auto=format&fit=crop&w=400&q=80',
    views: '800k',
    time: '1 year ago',
    isLive: false,
    description: 'After more than thirty years of service as one of the Navy\'s top aviators, Pete "Maverick" Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.',
    rating: 4.9,
    reviews: [
      { id: 'rev8', user: '80sKid', comment: 'A worthy sequel to a classic. Pure adrenaline!' },
    ],
    plot: 'After more than 30 years of service as one of the Navy\'s top aviators, Pete "Maverick" Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him. Training a detachment of Top Gun graduates for a specialized mission, Maverick must confront the ghosts of his past and his deepest fears, culminating in a mission that demands the ultimate sacrifice from those who choose to fly it.',
    actors: ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm'],
    genre: 'Action, Drama',
    director: 'Joseph Kosinski',
  },
  {
    id: 'tc-3',
    title: 'Edge of Tomorrow',
    channel: 'Warner Bros',
    thumbnail: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=400&q=80',
    views: '1.1M',
    time: '3 years ago',
    isLive: false,
    description: 'A soldier relives the same day in a war against aliens.',
    rating: 4.8,
    reviews: [],
    plot: 'Caught in a time loop, a soldier must find a way to save humanity.',
    actors: ['Tom Cruise', 'Emily Blunt'],
    genre: 'Action, Sci-Fi',
    director: 'Doug Liman',
  },
  {
    id: 'tc-4',
    title: 'Jack Reacher',
    channel: 'Paramount Pictures',
    thumbnail: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=400&q=80',
    views: '900k',
    time: '4 years ago',
    isLive: false,
    description: 'A former military investigator unravels a deadly conspiracy.',
    rating: 4.4,
    reviews: [],
    plot: 'Jack Reacher uncovers the truth behind a complex case.',
    actors: ['Tom Cruise', 'Rosamund Pike'],
    genre: 'Action, Thriller',
    director: 'Christopher McQuarrie',
  },
  {
    id: 'tc-5',
    title: 'Oblivion',
    channel: 'Universal Pictures',
    thumbnail: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    views: '750k',
    time: '5 years ago',
    isLive: false,
    description: 'A drone repairman discovers shocking secrets about Earth.',
    rating: 4.5,
    reviews: [],
    plot: 'Earth is not what it seems in this mind-bending sci-fi adventure.',
    actors: ['Tom Cruise', 'Andrea Riseborough'],
    genre: 'Sci-Fi, Adventure',
    director: 'Joseph Kosinski',
  },
  {
    id: 'tc-6',
    title: 'The Mummy',
    channel: 'Universal Pictures',
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
    views: '600k',
    time: '6 years ago',
    isLive: false,
    description: 'An ancient princess is awakened from her crypt beneath the desert.',
    rating: 4.0,
    reviews: [],
    plot: 'A modern-day adventure with ancient curses and epic battles.',
    actors: ['Tom Cruise', 'Sofia Boutella'],
    genre: 'Action, Adventure',
    director: 'Alex Kurtzman',
  },
  {
    id: 'tc-7',
    title: 'American Made',
    channel: 'Universal Pictures',
    thumbnail: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    views: '500k',
    time: '7 years ago',
    isLive: false,
    description: 'A pilot becomes a drug runner for the CIA.',
    rating: 4.2,
    reviews: [],
    plot: 'Based on the outrageous true story of Barry Seal.',
    actors: ['Tom Cruise', 'Domhnall Gleeson'],
    genre: 'Crime, Drama',
    director: 'Doug Liman',
  },
];

export const popularArtists = users.slice(0, 5).map(user => ({
  ...user,
  id: `pop-art-${user.id}`,
}));

export const yourFavouriteArtists = users.slice(2, 7).map(user => ({
  ...user,
  id: `fav-art-${user.id}`,
}));

export const chatMessages = [
  { id: '1', text: 'Hey! Hows it going?', sender: '1' },
  { id: '2', text: 'Not bad, just chilling. You?', sender: 'user0' },
  { id: '3', text: 'Same here. Did you watch the new movie?', sender: '1' },
  {
    id: 'poll1',
    type: 'poll',
    sender: '1',
    question: 'What should we watch tonight?',
    options: [
      { id: 'opt1', text: 'Action Movie', votes: 1 },
      { id: 'opt2', text: 'Comedy Special', votes: 0 },
      { id: 'opt3', text: 'Documentary', votes: 1 },
    ],
  },
  { id: '4', text: 'Not yet, is it any good?', sender: 'user0' },
];

export const currentUser = {
  id: 'user0',
  name: 'John Doe',
  username: 'johndoe',
  avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
  bio: 'Movie enthusiast. Collector of stories. Living one frame at a time.',
  followers: 1254,
  following: 132,
  watchlist: ['1', 'tc-2', '3', 'tc-1'],
};

export const topPicksByFriends = [...trendingVideos, ...popularTomCruise]
  .sort(() => 0.5 - Math.random())
  .slice(0, 5)
  .map(video => ({ ...video, id: `friend-pick-${video.id}` }));

// Update clubs to have 10 random movies each
function getRandomMovieIds(count) {
  const allIds = [
    ...trendingVideos.map(m => m.id),
    ...popularTomCruise.map(m => m.id),
  ];
  const shuffled = allIds.sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

clubs[0].movies = getRandomMovieIds(10);
clubs[1].movies = getRandomMovieIds(10);
clubs[2].movies = getRandomMovieIds(10);
clubs[3].movies = getRandomMovieIds(10); 